plugins {
  id 'java'
  id 'idea'
  id 'net.minecraftforge.gradle' version '6.0.+'
  id 'io.github.goooler.shadow' version '8.1.8'
}

def mod_file = getModFile("net.gegy1000.terrarium.Terrarium")
version = getModField("VERSION", mod_file)
group = "net.gegy1000"

base {
  archivesName = "terrarium"
}

java.toolchain.languageVersion = JavaLanguageVersion.of(8)

repositories {
  maven {
    url = "https://maven.gegy.dev"
    content {
      includeGroup "net.gegy1000"
      includeGroup "dev.gegy"
      includeGroup "org.tukaani"
    }
  }
  maven {
    url = "https://cursemaven.com"
    content {
      includeGroup "curse.maven"
    }
  }
  maven {
    url = "https://mvn.topobyte.de"
    content {
      includeGroup "com.vividsolutions"
    }
  }
  maven {
    url = "https://maven.daporkchop.net"
    content {
      includeGroup "io.github.opencubicchunks"
    }
  }
  mavenCentral()
  maven { url = "https://maven.minecraftforge.net/" }
}

configurations {
  embed
  implementation.extendsFrom(embed)
}

minecraft {
  mappings channel: "stable", version: "39-1.12"
  accessTransformer file('src/main/resources/META-INF/terrarium_at.cfg')
  accessTransformer file('src/main/resources/META-INF/terrarium_at_dev.cfg')

  runs {
    client {
    }
    server {
    }
    configureEach {
      workingDirectory = project.file('run')
      mods {
        "${project.name}" {
          source sourceSets.main
        }
      }
      // Configure Mixin for Cubic Chunks dependecy
      jvmArgs = [
          '-Xmx2G',
          '-Dfml.coreMods.load=io.github.opencubicchunks.cubicchunks.core.asm.coremod.CubicChunksCoreMod',
          '-Dmixin.env.compatLevel=JAVA_8',
          '-Dmixin.env.disableRefMap=true'
      ]
    }
  }
}

dependencies {
  minecraft 'net.minecraftforge:forge:1.12.2-14.23.5.2864'

  // optional dependencies
  implementation 'io.github.opencubicchunks:cubicchunks-api:1.12.2-0.0.1301.0-SNAPSHOT'
  implementation fg.deobf('io.github.opencubicchunks:cubicchunks:1.12.2-0.0.1301.0-SNAPSHOT')

  implementation fg.deobf('curse.maven:biomes-o-plenty-220318:3558882')
  implementation fg.deobf('curse.maven:dynamictrees-252818:3812473')

  // embedded dependencies
  embed 'dev.gegy:gengen:0.1.0-SNAPSHOT'
  embed 'net.gegy1000:just-now:0.1.0-SNAPSHOT'
  embed 'com.vividsolutions:jts:1.13'
  embed 'org.tukaani:xz-fork:1.8'
}

jar {
  archiveClassifier = 'slim'
  manifest {
    attributes "FMLAT": "terrarium_at.cfg"
    attributes "Maven-Artifact": "${project.group}:${project.archivesBaseName}:${project.version}"
    attributes "Timestamp": System.currentTimeMillis()
  }
  finalizedBy 'reobfJar'
}

shadowJar {
  archiveClassifier = ''
  configurations = [project.configurations.embed]
}

reobf {
  shadowJar { }
}

build.dependsOn reobfShadowJar

processResources {
  inputs.property "version", project.version

  filesMatching('mcmod.info') {
    expand 'version': project.version
  }
}

File getModFile(String fq_name) {
  return file("src/main/java/${fq_name.replace('.', '/')}.java")
}

String getModField(String type, File mod_file) {
  String field = ""
  String prefix = "public static final String $type = \""
  mod_file.eachLine { String s ->
    s = s.trim()
    if (s.startsWith(prefix)) {
      s = s.substring(prefix.length(), s.length() - 2)
      field = s
    }
  }
  return field
}

idea {
  module {
    downloadSources = true
    downloadJavadoc = true
  }
}

// ForgeGradle horrors beyond my comprehension

configurations.configureEach {
  resolutionStrategy {
    eachDependency {
      if (it.requested.group == 'org.ow2.asm' && it.requested.version == '6.0') {
        it.useVersion '5.2'
      }
    }
  }
  exclude group: 'net.minecraftforge', module: 'mergetool'
}

legacy {
  fixClasspath = false
}

sourceSets.configureEach {
  it.output.resourcesDir = it.output.classesDirs.getFiles().iterator().next()
}
