org.gradle.jvmargs=-Xmx1G

minecraft_version=1.20.4
minecraft_version_range=>=1.20.4

mod_id=terrarium
version=2.0.0
maven_group=dev.gegy

mod_name=Terrarium
mod_author=Gegy
description=Generation of the Earth in a new customizable world type.
license=LGPLv3
credits=NASA/JPL-Caltech, GEBCO Compilation Group, ESA Climate Change Initiative, ISRIC World Soil Info, OpenStreetMap Contributors, WorldClim, iNaturalist
sources=https://github.com/Gegy/Terrarium
issue_tracker=https://github.com/Gegy/Terrarium/issues

# Fabric
fabric_version=0.91.3+1.20.4
fabric_loader_version=0.15.3
