pluginManagement {
  repositories {
    gradlePluginPortal()
    mavenCentral()
    maven { url 'https://maven.fabricmc.net/' }
    maven { url 'https://repo.spongepowered.org/maven/' }
  }
  resolutionStrategy {
    eachPlugin {
      if (requested.id.toString() == 'org.spongepowered.mixin') {
        useModule("org.spongepowered:mixingradle:${requested.version}")
      }
    }
  }
}

plugins {
  id 'org.gradle.toolchains.foojay-resolver-convention' version '0.8.0'
}

rootProject.name = 'Terrarium'
include ':backend', ':common', ':fabric', ':tools'
