plugins {
  id 'net.neoforged.moddev'
}

base {
  archivesName = "$mod_id-common-$minecraft_version"
}

// TODO: Split client/server source
neoForge {
  neoFormVersion = neo_form_version
  parchment {
    minecraftVersion = parchment_minecraft
    mappingsVersion = parchment_version
  }

  ideSyncTask rootProject.tasks.named('generateModManifests')
}

dependencies {
  implementation project(':backend')

  compileOnly 'org.spongepowered:mixin:0.8.5'
  compileOnly 'io.github.llamalad7:mixinextras-common:0.3.5'
  annotationProcessor 'io.github.llamalad7:mixinextras-common:0.3.5'
}
